-- Savanna Explorer v4.38 — authenticated trip collaboration

create table if not exists public.trip_collaborators (
    trip_id uuid not null references public.user_trips(id) on delete cascade,
    user_id uuid not null references auth.users(id) on delete cascade,
    role text not null check (role in ('viewer', 'editor')),
    invited_by uuid not null references auth.users(id) on delete cascade,
    joined_at timestamptz not null default now(),
    primary key (trip_id, user_id)
);

create table if not exists public.trip_collaboration_invites (
    id uuid primary key default gen_random_uuid(),
    trip_id uuid not null references public.user_trips(id) on delete cascade,
    token uuid not null default gen_random_uuid() unique,
    role text not null check (role in ('viewer', 'editor')),
    created_by uuid not null references auth.users(id) on delete cascade,
    claimed_by uuid references auth.users(id) on delete set null,
    claimed_at timestamptz,
    expires_at timestamptz not null default (now() + interval '7 days'),
    revoked_at timestamptz,
    created_at timestamptz not null default now()
);

create table if not exists public.trip_activity (
    id bigint generated by default as identity primary key,
    trip_id uuid not null references public.user_trips(id) on delete cascade,
    actor_id uuid references auth.users(id) on delete set null,
    action text not null check (char_length(action) between 1 and 80),
    details jsonb not null default '{}'::jsonb check (jsonb_typeof(details) = 'object'),
    created_at timestamptz not null default now()
);

create index if not exists trip_collaborators_user_idx on public.trip_collaborators (user_id, joined_at desc);
create index if not exists trip_collaboration_invites_trip_idx on public.trip_collaboration_invites (trip_id, created_at desc);
create index if not exists trip_activity_trip_idx on public.trip_activity (trip_id, created_at desc);

alter table public.trip_collaborators enable row level security;
alter table public.trip_collaboration_invites enable row level security;
alter table public.trip_activity enable row level security;

drop policy if exists "Members can view trip collaborators" on public.trip_collaborators;
create policy "Members can view trip collaborators" on public.trip_collaborators for select to authenticated
    using (
        (select auth.uid()) = user_id
        or exists (
            select 1 from public.user_trips ut
            where ut.id = trip_id and ut.user_id = (select auth.uid())
        )
    );

drop policy if exists "Owners can view collaboration invites" on public.trip_collaboration_invites;
create policy "Owners can view collaboration invites" on public.trip_collaboration_invites for select to authenticated
    using (exists (
        select 1 from public.user_trips ut
        where ut.id = trip_id and ut.user_id = (select auth.uid())
    ));

drop policy if exists "Members can view trip activity" on public.trip_activity;
create policy "Members can view trip activity" on public.trip_activity for select to authenticated
    using (
        exists (
            select 1 from public.user_trips ut
            where ut.id = trip_id and ut.user_id = (select auth.uid())
        )
        or exists (
            select 1 from public.trip_collaborators tc
            where tc.trip_id = trip_activity.trip_id and tc.user_id = (select auth.uid())
        )
    );

create or replace function public.create_trip_collaboration_invite(p_client_id text, p_role text)
returns table (invite_id uuid, invite_token uuid, invite_role text, expires_at timestamptz)
language plpgsql
security definer
set search_path = public, auth, pg_temp
as $$
declare
    v_trip_id uuid;
begin
    if auth.uid() is null then raise exception 'Authentication required'; end if;
    if p_role not in ('viewer', 'editor') then raise exception 'Invalid collaboration role'; end if;

    select id into v_trip_id from public.user_trips
    where user_id = auth.uid() and client_id = p_client_id and deleted_at is null;
    if v_trip_id is null then raise exception 'Trip not found'; end if;

    return query
    insert into public.trip_collaboration_invites (trip_id, role, created_by)
    values (v_trip_id, p_role, auth.uid())
    returning id, token, role, trip_collaboration_invites.expires_at;

    insert into public.trip_activity (trip_id, actor_id, action, details)
    values (v_trip_id, auth.uid(), 'invite_created', jsonb_build_object('role', p_role));
end;
$$;

create or replace function public.accept_trip_collaboration_invite(p_token uuid)
returns table (trip_id uuid, data jsonb, access_role text, updated_at timestamptz)
language plpgsql
security definer
set search_path = public, auth, pg_temp
as $$
declare
    v_invite public.trip_collaboration_invites%rowtype;
    v_owner uuid;
begin
    if auth.uid() is null then raise exception 'Authentication required'; end if;

    select * into v_invite from public.trip_collaboration_invites
    where token = p_token for update;
    if v_invite.id is null or v_invite.revoked_at is not null or v_invite.expires_at <= now() then
        raise exception 'Invite is invalid or expired';
    end if;
    if v_invite.claimed_by is not null and v_invite.claimed_by <> auth.uid() then
        raise exception 'Invite has already been used';
    end if;

    select user_id into v_owner from public.user_trips where id = v_invite.trip_id and deleted_at is null;
    if v_owner is null then raise exception 'Trip is unavailable'; end if;
    if v_owner = auth.uid() then raise exception 'You already own this trip'; end if;

    insert into public.trip_collaborators (trip_id, user_id, role, invited_by)
    values (v_invite.trip_id, auth.uid(), v_invite.role, v_invite.created_by)
    on conflict (trip_id, user_id) do update set role = excluded.role, invited_by = excluded.invited_by;

    update public.trip_collaboration_invites
    set claimed_by = auth.uid(), claimed_at = coalesce(claimed_at, now())
    where id = v_invite.id;

    insert into public.trip_activity (trip_id, actor_id, action, details)
    values (v_invite.trip_id, auth.uid(), 'collaborator_joined', jsonb_build_object('role', v_invite.role));

    return query select ut.id, ut.data, v_invite.role, ut.updated_at
    from public.user_trips ut where ut.id = v_invite.trip_id;
end;
$$;

create or replace function public.get_my_trip_collaborations()
returns table (trip_id uuid, data jsonb, access_role text, updated_at timestamptz)
language sql
stable
security definer
set search_path = public, auth, pg_temp
as $$
    select ut.id, ut.data, tc.role, ut.updated_at
    from public.trip_collaborators tc
    join public.user_trips ut on ut.id = tc.trip_id
    where tc.user_id = auth.uid() and ut.deleted_at is null
    order by ut.updated_at desc;
$$;

create or replace function public.get_trip_collaboration(p_trip_id uuid)
returns table (trip_id uuid, data jsonb, access_role text, updated_at timestamptz)
language sql
stable
security definer
set search_path = public, auth, pg_temp
as $$
    select ut.id, ut.data,
        case when ut.user_id = auth.uid() then 'owner' else tc.role end,
        ut.updated_at
    from public.user_trips ut
    left join public.trip_collaborators tc
        on tc.trip_id = ut.id and tc.user_id = auth.uid()
    where ut.id = p_trip_id and ut.deleted_at is null
      and (ut.user_id = auth.uid() or tc.user_id = auth.uid())
    limit 1;
$$;

create or replace function public.save_trip_collaboration(p_trip_id uuid, p_data jsonb)
returns table (data jsonb, updated_at timestamptz)
language plpgsql
security definer
set search_path = public, auth, pg_temp
as $$
declare
    v_client_id text;
    v_allowed boolean;
begin
    if auth.uid() is null then raise exception 'Authentication required'; end if;
    if jsonb_typeof(p_data) <> 'object' or pg_column_size(p_data) > 1048576 then
        raise exception 'Invalid trip data';
    end if;

    select ut.client_id,
        (ut.user_id = auth.uid() or exists (
            select 1 from public.trip_collaborators tc
            where tc.trip_id = ut.id and tc.user_id = auth.uid() and tc.role = 'editor'
        ))
    into v_client_id, v_allowed
    from public.user_trips ut where ut.id = p_trip_id and ut.deleted_at is null;

    if not coalesce(v_allowed, false) then raise exception 'Editor access required'; end if;
    if p_data->>'id' is distinct from v_client_id then raise exception 'Trip identity cannot be changed'; end if;

    return query
    update public.user_trips ut set data = p_data, updated_at = now()
    where ut.id = p_trip_id
    returning ut.data, ut.updated_at;

    insert into public.trip_activity (trip_id, actor_id, action, details)
    values (p_trip_id, auth.uid(), 'trip_updated', '{}'::jsonb);
end;
$$;

create or replace function public.list_trip_collaborators(p_client_id text)
returns table (user_id uuid, email text, role text, joined_at timestamptz)
language sql
stable
security definer
set search_path = public, auth, pg_temp
as $$
    select tc.user_id, au.email::text, tc.role, tc.joined_at
    from public.user_trips ut
    join public.trip_collaborators tc on tc.trip_id = ut.id
    join auth.users au on au.id = tc.user_id
    where ut.user_id = auth.uid() and ut.client_id = p_client_id and ut.deleted_at is null
    order by tc.joined_at desc;
$$;

create or replace function public.list_trip_collaboration_invites(p_client_id text)
returns table (invite_id uuid, invite_token uuid, invite_role text, expires_at timestamptz, claimed boolean)
language sql
stable
security definer
set search_path = public, auth, pg_temp
as $$
    select ti.id, ti.token, ti.role, ti.expires_at, (ti.claimed_by is not null)
    from public.user_trips ut
    join public.trip_collaboration_invites ti on ti.trip_id = ut.id
    where ut.user_id = auth.uid() and ut.client_id = p_client_id and ut.deleted_at is null
      and ti.revoked_at is null and ti.claimed_by is null and ti.expires_at > now()
    order by ti.created_at desc;
$$;

create or replace function public.get_trip_activity(p_client_id text, p_limit integer default 12)
returns table (action text, actor_email text, details jsonb, created_at timestamptz)
language sql
stable
security definer
set search_path = public, auth, pg_temp
as $$
    select ta.action, coalesce(au.email::text, 'Former collaborator'), ta.details, ta.created_at
    from public.user_trips ut
    join public.trip_activity ta on ta.trip_id = ut.id
    left join auth.users au on au.id = ta.actor_id
    where ut.client_id = p_client_id and ut.deleted_at is null
      and (
        ut.user_id = auth.uid()
        or exists (select 1 from public.trip_collaborators tc where tc.trip_id = ut.id and tc.user_id = auth.uid())
      )
    order by ta.created_at desc
    limit least(greatest(p_limit, 1), 50);
$$;

create or replace function public.revoke_trip_collaboration_invite(p_invite_id uuid)
returns void language plpgsql security definer set search_path = public, auth, pg_temp as $$
declare v_trip_id uuid;
begin
    update public.trip_collaboration_invites ti set revoked_at = now()
    where ti.id = p_invite_id and exists (
        select 1 from public.user_trips ut where ut.id = ti.trip_id and ut.user_id = auth.uid()
    ) returning ti.trip_id into v_trip_id;
    if not found then raise exception 'Invite not found'; end if;
    insert into public.trip_activity (trip_id, actor_id, action, details)
    values (v_trip_id, auth.uid(), 'invite_revoked', '{}'::jsonb);
end;
$$;

create or replace function public.remove_trip_collaborator(p_client_id text, p_user_id uuid)
returns void language plpgsql security definer set search_path = public, auth, pg_temp as $$
declare v_trip_id uuid;
begin
    select id into v_trip_id from public.user_trips
    where user_id = auth.uid() and client_id = p_client_id and deleted_at is null;
    if v_trip_id is null then raise exception 'Trip not found'; end if;
    delete from public.trip_collaborators where trip_id = v_trip_id and user_id = p_user_id;
    if not found then raise exception 'Collaborator not found'; end if;
    insert into public.trip_activity (trip_id, actor_id, action, details)
    values (v_trip_id, auth.uid(), 'collaborator_removed', '{}'::jsonb);
end;
$$;

revoke all on function public.create_trip_collaboration_invite(text, text) from public, anon;
revoke all on function public.accept_trip_collaboration_invite(uuid) from public, anon;
revoke all on function public.get_my_trip_collaborations() from public, anon;
revoke all on function public.get_trip_collaboration(uuid) from public, anon;
revoke all on function public.save_trip_collaboration(uuid, jsonb) from public, anon;
revoke all on function public.list_trip_collaborators(text) from public, anon;
revoke all on function public.list_trip_collaboration_invites(text) from public, anon;
revoke all on function public.get_trip_activity(text, integer) from public, anon;
revoke all on function public.revoke_trip_collaboration_invite(uuid) from public, anon;
revoke all on function public.remove_trip_collaborator(text, uuid) from public, anon;

grant execute on function public.create_trip_collaboration_invite(text, text) to authenticated;
grant execute on function public.accept_trip_collaboration_invite(uuid) to authenticated;
grant execute on function public.get_my_trip_collaborations() to authenticated;
grant execute on function public.get_trip_collaboration(uuid) to authenticated;
grant execute on function public.save_trip_collaboration(uuid, jsonb) to authenticated;
grant execute on function public.list_trip_collaborators(text) to authenticated;
grant execute on function public.list_trip_collaboration_invites(text) to authenticated;
grant execute on function public.get_trip_activity(text, integer) to authenticated;
grant execute on function public.revoke_trip_collaboration_invite(uuid) to authenticated;
grant execute on function public.remove_trip_collaborator(text, uuid) to authenticated;
