-- Savanna Explorer v4.69 — authenticated editorial workspace
-- Bootstrap the first administrator only after this migration, in the Supabase SQL Editor:
-- insert into public.editorial_members (user_id, display_name, role)
-- select id, 'REAL DISPLAY NAME', 'admin' from auth.users where email = 'REAL ACCOUNT EMAIL';

create schema if not exists private;
revoke all on schema private from public, anon;

create table if not exists public.editorial_members (
    user_id uuid primary key references auth.users(id) on delete cascade,
    display_name text not null check (char_length(display_name) between 2 and 100),
    role text not null check (role in ('editor', 'approver', 'admin')),
    active boolean not null default true,
    created_by uuid references auth.users(id) on delete set null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.editorial_assignments (
    record_id text primary key check (record_id ~ '^(visa-summary|visa-matrix|border|park-fee|emergency|travel-advisory):[a-z0-9-]+$'),
    owner_id uuid not null references public.editorial_members(user_id),
    approver_id uuid references public.editorial_members(user_id),
    status text not null default 'draft' check (status in ('draft', 'in-review', 'changes-requested', 'approved', 'published', 'blocked')),
    approved_at timestamptz,
    published_at timestamptz,
    updated_by uuid not null references auth.users(id),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    check (approver_id is null or approver_id <> owner_id),
    check (status not in ('approved', 'published') or (approver_id is not null and approved_at is not null)),
    check (status <> 'published' or published_at is not null)
);

create table if not exists public.editorial_corrections (
    id uuid primary key default gen_random_uuid(),
    record_id text not null check (record_id ~ '^(visa-summary|visa-matrix|border|park-fee|emergency|travel-advisory):[a-z0-9-]+$'),
    owner_id uuid not null references public.editorial_members(user_id),
    status text not null default 'open' check (status in ('open', 'investigating', 'resolved', 'rejected')),
    summary text not null check (char_length(summary) between 5 and 1000),
    resolution text check (resolution is null or char_length(resolution) between 5 and 2000),
    opened_by uuid not null references auth.users(id),
    opened_at timestamptz not null default now(),
    closed_at timestamptz,
    updated_at timestamptz not null default now(),
    check (status not in ('resolved', 'rejected') or (closed_at is not null and resolution is not null)),
    check (closed_at is null or closed_at >= opened_at)
);

create table if not exists public.editorial_events (
    id bigint generated by default as identity primary key,
    record_id text not null check (record_id ~ '^(visa-summary|visa-matrix|border|park-fee|emergency|travel-advisory):[a-z0-9-]+$'),
    actor_id uuid references auth.users(id) on delete set null,
    event_type text not null check (char_length(event_type) between 1 and 80),
    detail jsonb not null default '{}'::jsonb check (jsonb_typeof(detail) = 'object'),
    created_at timestamptz not null default now()
);

create index if not exists editorial_assignments_owner_idx on public.editorial_assignments (owner_id, updated_at desc);
create index if not exists editorial_assignments_approver_idx on public.editorial_assignments (approver_id, updated_at desc);
create index if not exists editorial_corrections_record_idx on public.editorial_corrections (record_id, status, opened_at desc);
create index if not exists editorial_corrections_owner_idx on public.editorial_corrections (owner_id, status, updated_at desc);
create index if not exists editorial_events_record_idx on public.editorial_events (record_id, created_at desc);

alter table public.editorial_members enable row level security;
alter table public.editorial_assignments enable row level security;
alter table public.editorial_corrections enable row level security;
alter table public.editorial_events enable row level security;

create or replace function private.current_editorial_role()
returns text
language sql
stable
security definer
set search_path = ''
as $$
    select em.role
    from public.editorial_members em
    where em.user_id = (select auth.uid()) and em.active
    limit 1;
$$;

revoke all on function private.current_editorial_role() from public, anon;
grant usage on schema private to authenticated;
grant execute on function private.current_editorial_role() to authenticated;

drop policy if exists "Editorial members can view members" on public.editorial_members;
create policy "Editorial members can view members" on public.editorial_members for select to authenticated
    using ((select private.current_editorial_role()) is not null);

drop policy if exists "Editorial admins can add members" on public.editorial_members;
create policy "Editorial admins can add members" on public.editorial_members for insert to authenticated
    with check ((select private.current_editorial_role()) = 'admin');

drop policy if exists "Editorial admins can update members" on public.editorial_members;
create policy "Editorial admins can update members" on public.editorial_members for update to authenticated
    using ((select private.current_editorial_role()) = 'admin')
    with check ((select private.current_editorial_role()) = 'admin');

drop policy if exists "Editorial admins can remove members" on public.editorial_members;
create policy "Editorial admins can remove members" on public.editorial_members for delete to authenticated
    using ((select private.current_editorial_role()) = 'admin');

drop policy if exists "Editorial members can view assignments" on public.editorial_assignments;
create policy "Editorial members can view assignments" on public.editorial_assignments for select to authenticated
    using ((select private.current_editorial_role()) is not null);

drop policy if exists "Editorial admins can create assignments" on public.editorial_assignments;
create policy "Editorial admins can create assignments" on public.editorial_assignments for insert to authenticated
    with check ((select private.current_editorial_role()) = 'admin');

drop policy if exists "Editorial participants can update assignments" on public.editorial_assignments;
create policy "Editorial participants can update assignments" on public.editorial_assignments for update to authenticated
    using (
        (select private.current_editorial_role()) = 'admin'
        or owner_id = (select auth.uid())
        or approver_id = (select auth.uid())
    )
    with check (
        (select private.current_editorial_role()) = 'admin'
        or owner_id = (select auth.uid())
        or approver_id = (select auth.uid())
    );

drop policy if exists "Editorial admins can delete assignments" on public.editorial_assignments;
create policy "Editorial admins can delete assignments" on public.editorial_assignments for delete to authenticated
    using ((select private.current_editorial_role()) = 'admin');

drop policy if exists "Editorial members can view corrections" on public.editorial_corrections;
create policy "Editorial members can view corrections" on public.editorial_corrections for select to authenticated
    using ((select private.current_editorial_role()) is not null);

drop policy if exists "Editorial members can open corrections" on public.editorial_corrections;
create policy "Editorial members can open corrections" on public.editorial_corrections for insert to authenticated
    with check (
        (select private.current_editorial_role()) = 'admin'
        or owner_id = (select auth.uid())
    );

drop policy if exists "Editorial owners can update corrections" on public.editorial_corrections;
create policy "Editorial owners can update corrections" on public.editorial_corrections for update to authenticated
    using (
        (select private.current_editorial_role()) = 'admin'
        or owner_id = (select auth.uid())
    )
    with check (
        (select private.current_editorial_role()) = 'admin'
        or owner_id = (select auth.uid())
    );

drop policy if exists "Editorial admins can delete corrections" on public.editorial_corrections;
create policy "Editorial admins can delete corrections" on public.editorial_corrections for delete to authenticated
    using ((select private.current_editorial_role()) = 'admin');

drop policy if exists "Editorial members can view events" on public.editorial_events;
create policy "Editorial members can view events" on public.editorial_events for select to authenticated
    using ((select private.current_editorial_role()) is not null);

create or replace function private.guard_editorial_assignment()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_user uuid := auth.uid();
    v_role text := private.current_editorial_role();
begin
    if v_user is null or v_role is null then raise exception 'Editorial access required'; end if;

    if tg_op = 'INSERT' then
        if v_role <> 'admin' then raise exception 'Editorial administrator access required'; end if;
        if new.status not in ('draft', 'blocked') then
            raise exception 'New assignments must begin as draft or blocked';
        end if;
        new.created_at := now();
        new.updated_by := v_user;
    elsif tg_op = 'UPDATE' then
        if new.record_id is distinct from old.record_id then
            raise exception 'Editorial record IDs cannot be changed';
        end if;
        if new.created_at is distinct from old.created_at
            or new.approved_at is distinct from old.approved_at
            or new.published_at is distinct from old.published_at
            or new.updated_by is distinct from old.updated_by then
            raise exception 'Editorial workflow timestamps and actors are database managed';
        end if;
        if (new.owner_id is distinct from old.owner_id or new.approver_id is distinct from old.approver_id) then
            if v_role <> 'admin' then
                raise exception 'Only an editorial administrator can change assignment ownership';
            end if;
            if new.status in ('approved', 'published') then
                raise exception 'Reset approval before changing assignment ownership';
            end if;
        end if;
        if new.status is distinct from old.status then
            if new.status in ('approved', 'changes-requested') then
                if v_user is distinct from new.approver_id then
                    raise exception 'Only the assigned independent approver can approve work or request changes';
                end if;
                if old.status not in ('in-review', 'approved', 'changes-requested') then
                    raise exception 'The owner must submit work for review before an approval decision';
                end if;
            elsif new.status = 'published' then
                if v_role <> 'admin' then raise exception 'Editorial administrator access required to publish'; end if;
                if old.status <> 'approved' then raise exception 'Independent approval is required before publication'; end if;
            elsif new.status in ('draft', 'in-review', 'blocked') then
                if v_role <> 'admin' and v_user <> old.owner_id then
                    raise exception 'Owners can submit work for review or mark it blocked';
                end if;
            end if;
        elsif v_role <> 'admin' and v_user <> old.owner_id and v_user is distinct from old.approver_id then
            raise exception 'Assignment participant access required';
        end if;
        new.updated_by := v_user;
        new.updated_at := now();
    elsif tg_op = 'DELETE' then
        if v_role <> 'admin' then raise exception 'Editorial administrator access required'; end if;
        return old;
    end if;

    if not exists (
        select 1 from public.editorial_members
        where user_id = new.owner_id and active and role in ('editor', 'admin')
    ) then raise exception 'Assignment owner must be an active editor or administrator'; end if;
    if new.approver_id is not null and not exists (
        select 1 from public.editorial_members
        where user_id = new.approver_id and active and role in ('approver', 'admin')
    ) then raise exception 'Assignment approver must be an active approver or administrator'; end if;

    if new.status in ('approved', 'published') then
        new.approved_at := coalesce(new.approved_at, now());
    else
        new.approved_at := null;
    end if;
    if new.status = 'published' then
        new.published_at := coalesce(new.published_at, now());
    else
        new.published_at := null;
    end if;
    return new;
end;
$$;

create or replace function private.audit_editorial_assignment()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_record_id text;
    v_previous_status text;
    v_status text;
begin
    if tg_op = 'DELETE' then
        v_record_id := old.record_id;
        v_previous_status := old.status;
        v_status := null;
    elsif tg_op = 'INSERT' then
        v_record_id := new.record_id;
        v_previous_status := null;
        v_status := new.status;
    else
        v_record_id := new.record_id;
        v_previous_status := old.status;
        v_status := new.status;
    end if;
    insert into public.editorial_events (record_id, actor_id, event_type, detail)
    values (
        v_record_id,
        auth.uid(),
        case when tg_op = 'INSERT' then 'assignment-created' when tg_op = 'DELETE' then 'assignment-removed' else 'assignment-updated' end,
        jsonb_build_object(
            'previousStatus', v_previous_status,
            'status', v_status
        )
    );
    if tg_op = 'DELETE' then return old; end if;
    return new;
end;
$$;

create or replace function private.guard_editorial_correction()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_user uuid := auth.uid();
    v_role text := private.current_editorial_role();
begin
    if v_user is null or v_role is null then raise exception 'Editorial access required'; end if;

    if tg_op = 'INSERT' then
        if v_role <> 'admin' and new.owner_id <> v_user then
            raise exception 'Editors may only open corrections they own';
        end if;
        new.opened_by := v_user;
        new.opened_at := now();
    elsif tg_op = 'UPDATE' then
        if v_role <> 'admin' then
            if old.owner_id <> v_user then raise exception 'Correction owner access required'; end if;
            if new.record_id is distinct from old.record_id
                or new.owner_id is distinct from old.owner_id
                or new.opened_by is distinct from old.opened_by
                or new.opened_at is distinct from old.opened_at then
                raise exception 'Only an editorial administrator can reassign a correction';
            end if;
        end if;
        new.updated_at := now();
    elsif tg_op = 'DELETE' then
        if v_role <> 'admin' then raise exception 'Editorial administrator access required'; end if;
        return old;
    end if;

    if new.status in ('resolved', 'rejected') then
        if new.resolution is null or char_length(new.resolution) < 5 then
            raise exception 'A correction resolution is required before closure';
        end if;
        new.closed_at := coalesce(new.closed_at, now());
    else
        new.closed_at := null;
    end if;
    return new;
end;
$$;

create or replace function private.audit_editorial_correction()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_record_id text;
    v_correction_id uuid;
    v_status text;
begin
    if tg_op = 'DELETE' then
        v_record_id := old.record_id;
        v_correction_id := old.id;
        v_status := null;
    else
        v_record_id := new.record_id;
        v_correction_id := new.id;
        v_status := new.status;
    end if;
    insert into public.editorial_events (record_id, actor_id, event_type, detail)
    values (
        v_record_id,
        auth.uid(),
        case when tg_op = 'INSERT' then 'correction-opened' when tg_op = 'DELETE' then 'correction-removed' else 'correction-updated' end,
        jsonb_build_object(
            'correctionId', v_correction_id,
            'status', v_status
        )
    );
    if tg_op = 'DELETE' then return old; end if;
    return new;
end;
$$;

drop trigger if exists guard_editorial_assignment on public.editorial_assignments;
create trigger guard_editorial_assignment before insert or update or delete on public.editorial_assignments
for each row execute function private.guard_editorial_assignment();

drop trigger if exists audit_editorial_assignment on public.editorial_assignments;
create trigger audit_editorial_assignment after insert or update or delete on public.editorial_assignments
for each row execute function private.audit_editorial_assignment();

drop trigger if exists guard_editorial_correction on public.editorial_corrections;
create trigger guard_editorial_correction before insert or update or delete on public.editorial_corrections
for each row execute function private.guard_editorial_correction();

drop trigger if exists audit_editorial_correction on public.editorial_corrections;
create trigger audit_editorial_correction after insert or update or delete on public.editorial_corrections
for each row execute function private.audit_editorial_correction();

revoke all on table public.editorial_members from anon, authenticated;
revoke all on table public.editorial_assignments from anon, authenticated;
revoke all on table public.editorial_corrections from anon, authenticated;
revoke all on table public.editorial_events from anon, authenticated;

grant select, insert, update, delete on table public.editorial_members to authenticated;
grant select, insert, update, delete on table public.editorial_assignments to authenticated;
grant select, insert, update, delete on table public.editorial_corrections to authenticated;
grant select on table public.editorial_events to authenticated;

revoke all on function private.guard_editorial_assignment() from public, anon, authenticated;
revoke all on function private.audit_editorial_assignment() from public, anon, authenticated;
revoke all on function private.guard_editorial_correction() from public, anon, authenticated;
revoke all on function private.audit_editorial_correction() from public, anon, authenticated;
